### ISSUE TITLE
Suggest changing default transformation to the cumulative normal distribution function 

### ISSUE THREAD

**Issue by oddvarlia** [equinor/APS-Facies#37]
The purpose is to ensure that the CDF function for normal distribution is choosen per default when not using spatial trends in GRF's.
The effect of using CDF for normal distribution as transformation is that any update of a grid cell value (i,j,k) for a GRF field only will affect the same grid cell (i,j,k) of the facies realization when running APS as part of a RMS forward model in ERT with localisation. In particular when running with distance- based localisation an update close to a well for a GRF may end up in an update of facies outside the range of the distance from the observation when using empiric cumulative distribution function as transformation. But note that empiric transformation is necessary if GRF's have spatial trends, and APS plugin will ensure that this transformation always is used in this case.

**Comment by sebastianvitterso** [comment]
Already done, actually.
